spring.datasource.url=jdbc:mysql://localhost:3306/emaildb
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

flask.api.url=http://127.0.0.1:5000/predict

#flask.api.url=http://localhost:5000/predict

#USE email_spam;
#SHOW TABLES;
#select * From email_entity;
#Optional : DESCRIBE email_entity; // Check table structure